#
# Build documentation and deploy
#
name: Docs

on:
  # pull_request:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/**'

defaults:
  run:
    # default to use bash shell
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Cancel previous runs that are not completed
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build the website
        run: make -C docs clean html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
        if: github.event_name == 'push'
