[dataset.earth_age]
name = "earth_age"
title = "EarthByte Global Earth Seafloor Crustal Age"
logo = "/_static/EarthByte_logo_small.png"
image = "/_static/GMT_age.png"
description = """
Numerous geodynamic and geophysical studies consider both the seafloor depth and
the seafloor crustal age. `EarthByte <https://www.earthbyte.org/>`_ has pioneered
the creation of crustal age grids since 1997 and we offer their latest version for
remote use in GMT.
"""
cpt = "@earth_age.cpt"


resolutions = ["01d", "30m", "20m", "15m", "10m", "06m", "05m*", "04m*", "03m*", "02m*", "01m*"]
registrations = ["g,p", "g,p","g,p","g,p","g,p","g,p","g,p","g,p", "g,p","g,p", "g"]